package com.example.kamenriderdesiregrandfighter

class Constant {
    companion object {
        const val BASE_FORM = "Base"
        const val UPGRADE_FORM = "Upgrade"
        const val SUPER_FORM = "Super"
        const val FINAL_FORM = "Final"
        const val GEATS = "Geats"
        const val RYUKI = "Ryuki"
        const val OOO = "OOO"
        const val KABUTO = "Kabuto"
        const val GAIM = "Gaim"
        const val FAIZ = "Faiz"
        const val UNSELECTED = "Unselected"
        const val PLAYER_ONE = "Player 1"
        const val PLAYER_TWO = "Player 2"
        const val MAIN_MENU = "Main Menu"
        const val SELECTION_MENU = "Selection"
        const val COMBAT = "Combat"
        const val SINGLE_PLAYER = "Single-player"
        const val MULTI_PLAYER = "Multi-player"
        const val GAME_MODE = "GameMode"
        const val FIGHTER_SELECTION = "Fighter Selection"
        const val CHOSEN1 = "choosing character 1"
        const val CHOSEN2 = "choosing character 2"
        const val FORM_CHANGE = "form change"
        const val HEALTH_UP = "health up"
        const val HEALTH_DOWN = "health down"
        const val ENERGY_UP = "energy up"
        const val ENERGY_DOWN = "energy down"
        const val MAX_ENERGY = 100
        const val ATTACK_UP = "attack up"
        const val ATTACK_DOWN = "attack down"
        const val ATTACK_SET = "attack set"
        const val DEFENSE_UP = "defense up"
        const val DEFENSE_DOWN = "defense down"
        const val DEFENSE_SET = "defense set"
        const val SPEED_UP = "speed up"
        const val SPEED_DOWN = "speed down"
        const val SPEED_SET = "speed set"
        const val ACCURACY_UP = "accuracy up"
        const val ACCURACY_DOWN = "accuracy down"
        const val ACCURACY_SET = "accuracy set"
        const val LUCK_UP = "luck up"
        const val LUCK_DOWN = "luck down"
        const val LUCK_SET = "luck set"
        const val GAUGE_UP = "gauge up"
        const val GAUGE_DOWN = "gauge down"
        const val MAX_GAUGE = 10
        const val TURN_CHANGE = "turn change"
        const val GAME_OVER = "Game Over"
        const val WINNER = "winner"
        const val STATUS_MESSAGE = "special status"
        const val MESSAGE = "message"
        const val IMAGE_ID = "image id"
        const val NOT_ENOUGH_SP = "Not Enough SP"
        const val NOT_ENOUGH_RP = "Not Enough RP"
    }
}